### ISSUE TITLE
根据你的源码，改了下，发现动画不出来

### ISSUE THREAD

**Issue by huangche007** [xiaoluoboding/vue-stroll#3]
你好，今天看到了你这个项目，demo还是蛮不错的，自己看后很兴奋，于是乎准备将其加入到自己的项目中，看了下你的源代码，自己跟着改了下，发现动画没有出来，能否给我一个联系方式交流下，谢谢！

**Comment by xiaoluoboding** [comment]
目前已更新0.5.0，支持vue2.x，你更新试下。
